language: python
python:
  - "3.4"
install: 
  - sudo apt-get update
  - sudo apt-get install portaudio19-dev
  - pip install -r requirements.txt
  - pip install nose
  - pip install coveralls

script: nosetests ./tests --with-coverage --cover-package=./anki

after_success:
  - coveralls
